title: NetBird Client
description: Connect your devices into a secure WireGuard®-based overlay network with SSO, MFA and granular
  access controls.
icon: https://media.sys.truenas.net/apps/netbird-client/icons/icon.svg
categories:
- networking
keywords:
- vpn
- netbird
- wireguard
home: https://netbird.io/
screenshots: []
train: community
truenas_name: netbird-client
status: draft
managed: generated
upstream:
  version: 1.1.52
  app_version: 0.80.0
  questions_sha: 1cd63b65cb236afa26053c35aac1774c42b4c16469537231b86630c35740e294
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/netbird-client
notes: []
