title: Warracker
description: Warracker is an open-source web application to manage product warranties, track expiration
  dates, and store related documents.
icon: https://media.sys.truenas.net/apps/warracker/icons/icon.png
categories:
- productivity
keywords:
- warranty
- expiration
home: https://github.com/sassanix/Warracker
screenshots:
- https://media.sys.truenas.net/apps/warracker/screenshots/screenshot1.png
train: community
truenas_name: warracker
status: draft
managed: generated
upstream:
  version: 1.2.31
  app_version: 0.10.1.14
  questions_sha: 0aedfdc453fe4b714835942b024031392b11d7bd42513a17f2b269f89a8e5104
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/warracker
notes: []
curated: true
