title: Shelfmark
description: Shelfmark is a self-hosted web interface for searching and downloading books and audiobooks
  from multiple sources.
icon: https://media.sys.truenas.net/apps/shelfmark/icons/icon.png
categories:
- media
keywords:
- media
- ebooks
home: https://github.com/calibrain/shelfmark
screenshots: []
train: community
truenas_name: shelfmark
status: draft
managed: generated
upstream:
  version: 1.0.25
  app_version: v1.4.0
  questions_sha: d9dbdf3a28b57037e5c51b5cd3439bdbf435cbc89dd65a138c6e318143b9ec43
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/shelfmark
notes: []
