title: Recyclarr
description: Recyclarr synchronizes recommended settings from the TRaSH guides to your Sonarr/Radarr instances.
icon: https://media.sys.truenas.net/apps/recyclarr/icons/icon.png
categories:
- media
keywords:
- sync
- sonarr
- radarr
home: https://recyclarr.dev
screenshots: []
train: community
truenas_name: recyclarr
status: draft
managed: generated
upstream:
  version: 1.3.20
  app_version: 8.7.2
  questions_sha: 42556ffdc347469c40d98a8db048fa558533aa184a546dc8772ed86f2f896aac
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/recyclarr
notes: []
