title: Iconik Storage Gateway
description: The iconik Storage Gateway (ISG) allows you to use your on-premise storage with iconik in
  the cloud.
icon: https://media.sys.truenas.net/apps/iconik-storage-gateway/icons/icon.svg
categories:
- productivity
keywords:
- iconik
home: https://iconik.io
screenshots: []
train: community
truenas_name: iconik-storage-gateway
status: draft
managed: generated
upstream:
  version: 1.1.7
  app_version: 3.15.4
  questions_sha: ce2b36fa6f82c891dbc3494245974ca24ebfcd6cfa963613b273a0e9c3ed14c1
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/iconik-storage-gateway
notes: []
