title: AdventureLog
description: Self-hostable travel tracker and trip planner.
icon: https://media.sys.truenas.net/apps/adventurelog/icons/icon.svg
categories:
- productivity
keywords:
- adventure
- location
- tracker
- planner
home: https://adventurelog.app/
screenshots: []
train: community
truenas_name: adventurelog
status: draft
managed: generated
upstream:
  version: 1.3.30
  app_version: v0.13.0
  questions_sha: 12326be2718a5c7724942db5213a076808fe5492ecfc20e8e3bec792471a6c3a
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/adventurelog
notes: []
