title: KitchenOwl
description: KitchenOwl is a self-hosted grocery list and recipe manager. The backend is made with Flask
  and the frontend with Flutter. Easily add items to your shopping list before you go shopping. You can
  also create recipes and add items based on what you want to cook.
icon: https://media.sys.truenas.net/apps/kitchenowl/icons/icon.png
categories:
- productivity
keywords:
- grocery list
- recipe manager
- shopping list
home: https://kitchenowl.org/
screenshots: []
train: community
truenas_name: kitchenowl
status: draft
managed: generated
upstream:
  version: 1.2.35
  app_version: v0.7.10
  questions_sha: b4f623cbd2352be797899e31d171f491199d71353eaf7cd27588ab46acaf0a16
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/kitchenowl
notes: []
