title: Transmission
description: Transmission is designed for easy, powerful use.
icon: https://media.sys.truenas.net/apps/transmission/icons/icon.svg
categories:
- media
keywords:
- media
- torrent
- download
home: https://transmissionbt.com/
screenshots: []
train: community
truenas_name: transmission
status: draft
managed: generated
upstream:
  version: 1.3.10
  app_version: 4.1.3
  questions_sha: 823ee2b4513a60b596ed79f6f51b15ca30110fe3aee78b7c99f7a4f5e46e004a
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/transmission
notes: []
