title: Scrypted
description: Scrypted is a high performance video integration and automation platform
icon: https://media.sys.truenas.net/apps/scrypted/icons/icon.png
categories:
- home-automation
keywords:
- video
- automation
home: https://www.scrypted.app/
screenshots: []
train: community
truenas_name: scrypted
status: draft
managed: generated
upstream:
  version: 1.1.12
  app_version: v0.147.0-noble-full
  questions_sha: b9e15bd8988e2fa7d6efeff1c6c24b9f3981e2152c29500f6ebceb2f2b459db3
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/scrypted
notes: []
