title: Paperless AI
description: The most advanced AI companion for Paperless-NGX. Transform your document management with
  powerful AI-driven automation and insights.
icon: https://media.sys.truenas.net/apps/paperless-ai/icons/icon.png
categories:
- productivity
keywords:
- paperless
- ai
- automation
home: https://clusterzx.github.io/paperless-ai/
screenshots: []
train: community
truenas_name: paperless-ai
status: draft
managed: generated
upstream:
  version: 1.1.7
  app_version: 3.0.9
  questions_sha: 19dc8eb0bae854e07ea6e0573d463d796b43c785329a68f279760f39e17e51f0
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/paperless-ai
notes: []
