title: Deluge
description: Deluge is a lightweight, Free Software, cross-platform BitTorrent client.
icon: https://media.sys.truenas.net/apps/deluge/icons/icon.png
categories:
- media
keywords:
- torrent
- download
home: https://deluge-torrent.org
screenshots: []
train: community
truenas_name: deluge
status: draft
managed: generated
upstream:
  version: 1.3.7
  app_version: 2.2.0
  questions_sha: e712048efdcf8ab6d930d884f1e6579a4bea5c0c50e6d3cec1867ab0bd9d8de7
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/deluge
notes: []
