title: Draw.io
description: Draw.io is a whiteboarding / diagramming software application.
icon: https://media.sys.truenas.net/apps/drawio/icons/icon.png
categories:
- productivity
keywords:
- diagram
- whiteboard
home: https://www.drawio.com
screenshots:
- https://media.sys.truenas.net/apps/drawio/screenshots/screenshot1.png
- https://media.sys.truenas.net/apps/drawio/screenshots/screenshot2.png
- https://media.sys.truenas.net/apps/drawio/screenshots/screenshot3.png
train: community
truenas_name: drawio
status: draft
managed: generated
upstream:
  version: 1.4.46
  app_version: 32.0.1
  questions_sha: 86cd2f6472169918c17d1c69b602789467d783d3ff3b2b9d1b29325d6bbd3035
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/drawio
notes: []
curated: true
