title: Ghostfolio
description: Open Source Wealth Management Software.
icon: https://media.sys.truenas.net/apps/ghostfolio/icons/icon.svg
categories:
- financial
keywords:
- finance
home: https://ghostfol.io/
screenshots: []
train: community
truenas_name: ghostfolio
status: draft
managed: generated
upstream:
  version: 1.0.35
  app_version: 3.78.0
  questions_sha: a96170604075600c033692bef10e5fbcae1a01e72371e9e10519398bc19187d8
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/ghostfolio
notes: []
