title: Organizr
description: Organizr is a HTPC/Homelab Services Organizer - Written in PHP
icon: https://media.sys.truenas.net/apps/organizr/icons/icon.png
categories:
- media
keywords:
- dashboard
- organizr
home: https://github.com/causefx/Organizr
screenshots:
- https://media.sys.truenas.net/apps/organizr/screenshots/screenshot1.webp
- https://media.sys.truenas.net/apps/organizr/screenshots/screenshot2.webp
train: community
truenas_name: organizr
status: draft
managed: generated
upstream:
  version: 1.3.7
  app_version: latest
  questions_sha: 1e7dfc7b4f491421b47a8d714c4c95e66d799741d1cfcf822d892efc655d4b75
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/organizr
notes: []
