title: Factorio Server
description: Factorio headless server in a Docker container
icon: https://media.sys.truenas.net/apps/factorio/icons/icon.png
categories:
- games
keywords:
- games
- server
- factorio
home: https://factorio.com/
screenshots: []
train: community
truenas_name: factorio
status: draft
managed: generated
upstream:
  version: 1.1.10
  app_version: stable-2.0.77
  questions_sha: b002853d671445020063c212c807cf0ab36a19a4356a3cee0523f5eec8155d27
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/factorio
notes: []
