title: Stalwart
description: All-in-one Mail & Collaboration server. Secure, scalable and fluent in every protocol (IMAP,
  JMAP, SMTP, CalDAV, CardDAV, WebDAV).
icon: https://media.sys.truenas.net/apps/stalwart/icons/icon.svg
categories:
- productivity
keywords:
- mail
- collaboration
home: https://stalw.art/
screenshots: []
train: community
truenas_name: stalwart
status: draft
managed: generated
upstream:
  version: 2.0.16
  app_version: v0.16.24
  questions_sha: 367213fb437128bd3a20a2777476bf9ace37af8dcfb410f22f2360ba7df515f9
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/stalwart
notes: []
