title: Immich Frame
description: An awesome way to display your photos as a digital photo frame
icon: https://media.sys.truenas.net/apps/immich-frame/icons/icon.svg
categories:
- media
keywords:
- media
home: https://immichframe.dev/
screenshots: []
train: community
truenas_name: immich-frame
status: draft
managed: generated
upstream:
  version: 1.0.7
  app_version: v1.0.38.0
  questions_sha: 1b34b80aebb650406eab8177c3e9876595037cd6d7c8d1318eac0d4f6695f225
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/immich-frame
notes: []
