title: LocalAI
description: The free, Open Source alternative to OpenAI, Claude and others. Self-hosted and local-first.
icon: https://media.sys.truenas.net/apps/localai/icons/icon.png
categories:
- ai
keywords:
- ai
- llm
home: https://localai.io/
screenshots: []
train: community
truenas_name: localai
status: draft
managed: generated
upstream:
  version: 1.1.36
  app_version: v4.11.0
  questions_sha: 4733e8c493777e3da587c138be2ec27fd2db26ea65926029621c5621e926f628
  commit: fcb435722d2a50f84ce5457b3288b72b8d170ac5
  source: https://github.com/truenas/apps/tree/master/ix-dev/community/localai
notes: []
